PracticaMvcMichelyPinto/Models/ErrorViewModel.cs
namespace PracticaMvcMichelyPinto.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PracticaMvcMichelyPinto/Models/ImagenZapatilla.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PracticaMvcMichelyPinto.Models
{
    [Table("IMAGENESZAPASPRACTICA")]

    public class ImagenZapatilla
    {
        [Key]
        [Column("IDIMAGEN")]
        public int IdImage { get; set; }
        [Column("IDPRODUCTO")]
        public int IdProducto { get; set; }
        [Column("IMAGEN")]
        public string Imagen { get; set; }
    }
}

PracticaMvcMichelyPinto/Models/ModelPaginacion.cs
namespace PracticaMvcMichelyPinto.Models
{
    public class ModelPaginacion
    {
        public int NumeroRegistros { get; set; }
        public List<ImagenZapatilla> Imagenes { get; set; }
    }
}

PracticaMvcMichelyPinto/Models/Zapatilla.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PracticaMvcMichelyPinto.Models
{

    [Table("ZAPASPRACTICA")]
    public class Zapatilla
    {
        [Key]
        [Column("IDPRODUCTO")]
        public int IdProducto { get; set; }

        [Column("NOMBRE")]
        public string Nombre { get; set; }
        [Column("DESCRIPCION")]
        public string Descripcion { get; set; }
        [Column("PRECIO")]
        public int Precio { get; set; }
    }
}

PracticaMvcMichelyPinto/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PracticaMvcMichelyPinto.Models;
using System.Diagnostics;

namespace PracticaMvcMichelyPinto.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PracticaMvcMichelyPinto/Controllers/ZapatillasController.cs
using Microsoft.AspNetCore.Mvc;
using PracticaMvcMichelyPinto.Models;
using PracticaMvcMichelyPinto.Repositories;
using System.Drawing;

namespace PracticaMvcMichelyPinto.Controllers
{
    public class ZapatillasController : Controller
    {
        private RepositoryZapatilla repo;
        public ZapatillasController(RepositoryZapatilla repo)
        {
            this.repo = repo;
        }
        public async Task<IActionResult> Zapatillas()
        {
            List<Zapatilla> zapatillas = await this.repo.GetZapatillasAsync();
            return View(zapatillas);
        }
        public async Task<IActionResult> Details(int idproducto)
        {
            Zapatilla zap = await this.repo.FindZapatillaAsync(idproducto);
            return View(zap);
        }
        public async Task<IActionResult> _PartialPaginacion(int? posicion,int idproducto)
        {
            if (posicion == null)
            {
                posicion = 1;
            }
           
           
                ModelPaginacion model = await
                    this.repo.GetImagen(posicion.Value,idproducto);
                ViewData["REGISTROS"] = model.NumeroRegistros;
                ViewData["IDPRODUCTO"] = idproducto;
                ViewData["POSICION"] = posicion;
                int siguiente = posicion.Value + 1;
                //DEBEMOS COMPROBAR QUE NO PASAMOS DEL NUMERO DE REGISTROS
                if (siguiente > model.NumeroRegistros)
                {
                    //EFECTO OPTICO
                    siguiente = model.NumeroRegistros;
                }
                int anterior = posicion.Value - 1;
                if (anterior < 1)
                {
                    anterior = 1;
                }
                ViewData["ULTIMO"] = model.NumeroRegistros;
                ViewData["SIGUIENTE"] = siguiente;
                ViewData["ANTERIOR"] = anterior;
                ViewData["POSICION"] = posicion;
                return PartialView("_PartialPaginacion", model.Imagenes);
           
        }
        public async Task<IActionResult> Insertar()
        {

            var zapatillas = await this.repo.GetZapatillasAsync();
            ViewData["ZAPATILLAS"] = zapatillas;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Insertar(List<string> imagen)
        {

            //this.repo.InsertarImagen(imagen);
            return View();
        }

    }
}

PracticaMvcMichelyPinto/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PracticaMvcMichelyPinto/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PracticaMvcMichelyPinto</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PracticaMvcMichelyPinto.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PracticaMvcMichelyPinto</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Zapatillas" asp-action="Zapatillas">Zapatillas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Zapatillas" asp-action="Insertar">Insertar</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - PracticaMvcMichelyPinto - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PracticaMvcMichelyPinto/Views/Zapatillas/Details.cshtml
@model PracticaMvcMichelyPinto.Models.Zapatilla

@{
    ViewData["Title"] = "Detalle";
}



<div>
    <h4>Zapatilla</h4>
    <hr />

    <div class="card" style="width: 35rem;">
        <div class="card-body">
            <h5 class="card-title">Nombre @Model.Nombre</h5>
   
            <p class="card-text">@Model.Descripcion</p>
            <p class="card-text">Precio: @Model.Precio</p>

            
        </div>
    </div>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>
<div id="container"> </div>
@section Scripts{
    <script>
        function loadImagen(posicion) {
            $(document).ready(function(){
                $("#container").load("/Zapatillas/_PartialPaginacion?posicion="
                    + posicion + "&idproducto=" + @Model.IdProducto);
                console.log(posicion);
            })
        }
        loadImagen(1);
    </script>
}
 

PracticaMvcMichelyPinto/Views/Zapatillas/Insertar.cshtml
@model Zapatilla
@{
    List<Zapatilla> zapatillas = ViewData["ZAPATILLAS"] as List<Zapatilla>;
}
<p>
    <a asp-controller="Zapatillas" asp-action="Zapatillas">
        Volver a Index
    </a>
</p>
<h1>Nuevas imagenes zapatillas</h1>
<form method="post">
    <h2>Seleccione una zapatilla:</h2>
    <select class="form-select" aria-label="Default select example">
        @foreach (Zapatilla zap in zapatillas)
        {
            <option value="@zap.IdProducto">@zap.Nombre</option>
        }
        
    </select>
    <input type="text" name="imagen" />
    <label>Imagen</label>
  
    <button class="btn btn-info">
        Insertar imagen
    </button>
</form>

@* @section Scripts{
    No me va a dar tiempo
} *@

PracticaMvcMichelyPinto/Views/Zapatillas/Zapatillas.cshtml
@model IEnumerable<PracticaMvcMichelyPinto.Models.Zapatilla>

@{
    ViewData["Title"] = "Zapatillas";
}

<h1>Zapatillas</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdProducto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Precio)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdProducto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Precio)
            </td>
           @*  <td>
                @Html.ActionLink("Details", "Details", new { id=item.IdProducto }) |
            </td> *@
            <td>
                    <a asp-controller="Zapatillas"
                       asp-action="Details"
                       asp-route-idproducto="@item.IdProducto">
                        Detalle
                    </a>
            </td>
        </tr>
}
    </tbody>
</table>

PracticaMvcMichelyPinto/Views/Zapatillas/_PartialPaginacion.cshtml
@model PracticaMvcMichelyPinto.Models.ImagenZapatilla
<h1>ZapatillasImagenes</h1>

<div>
    <ul class="list-group list-group-horizontal">
        <li class="list-group-item">
            <button class="btn btn-dark" onclick="loadImagen(1)" id="primero">
                Primero
            </button>
        </li>
        <li class="list-group-item">
            <button class="btn btn-dark" onclick="loadImagen(@ViewData["ANTERIOR"])" id="anterior">
                Anterior
            </button>
        </li>
        <li class="list-group-item">
            <button class="btn btn-dark" onclick="loadImagen(@ViewData["SIGUIENTE"])" id="siguiente">
                Siguiente
            </button>
        </li>
        <li class="list-group-item">
            <button class="btn btn-dark" onclick="loadImagen(@ViewData["ULTIMO"])" id="ultimo">
                Último
            </button>
        </li>
    </ul>

</div>
<div id="container" class="card" style="width: 18rem;">
      
        <img class="card-img-top" src="@Model.Imagen" alt="Card image cap">
    
</div>